---
base_dir: /var/vcap.local/dea2
pid_filename: /var/vcap/sys/run/dea2.pid
nats_uri: nats://localhost:4222/
logging:
  level: debug

#helpful for development
reset_at_startup: true

warden_socket_path: /tmp/warden.sock

resources:
  node_limits:
    max_memory: 4096
    max_disk:   409600
    max_instances: 100
  default_app_quota:
    mem_quota: 512
    disk_quota: 256

# This is where the execution agent determines its available runtimes.
# version flags are assumed to be '-v' unless noted below.

runtimes:
  ruby18:
    executable: /usr/bin/ruby
    version: 1.8.7
    version_flag: "-e 'puts RUBY_VERSION'"
    additional_checks: "-e 'puts RUBY_PATCHLEVEL >= 174'"
    environment:
  ruby19:
    executable: ruby
    version: 1.9.2
    version_flag: "-e 'puts RUBY_VERSION'"
    additional_checks: "-e 'puts RUBY_PATCHLEVEL >= 180'"
    environment:
  node:
    executable: node
    version: 0.4.12
    version_flag: '-v'
    environment:
    debug_env:
      run:
        - NODE_ARGS="--debug=$VCAP_DEBUG_PORT"
      suspend:
        - NODE_ARGS="--debug-brk=$VCAP_DEBUG_PORT"
  node06:
    executable: node
    version: 0.6.8
    version_flag: '-v'
    environment:
    debug_env:
      run:
        - NODE_ARGS="--debug=$VCAP_DEBUG_PORT"
      suspend:
        - NODE_ARGS="--debug-brk=$VCAP_DEBUG_PORT"
  java:
    executable: java
    version: 1.6.0
    version_flag: '-version'
    environment:
    debug_env:
      run:
        - JAVA_OPTS="$JAVA_OPTS -Xdebug -Xrunjdwp:transport=dt_socket,address=$VCAP_DEBUG_PORT,server=y,suspend=n"
      suspend:
        - JAVA_OPTS="$JAVA_OPTS -Xdebug -Xrunjdwp:transport=dt_socket,address=$VCAP_DEBUG_PORT,server=y,suspend=y"
  php:
    executable: php
    version: 5.3.[2-6]
    version_flag: '-v'
    environment:
  erlangR14B02:
    executable: /var/vcap/runtimes/erlang-R14B02/bin/erl
    version: ".* 5.8.3"
    version_flag: '-version'
    environment:
  python2:
    executable: python
    version: 2.6.5
    version_flag: '--version'
    environment:

# Used for /healthz and /vars endpoints. If not provided random
# values will be generated on component start. Uncomment to use
# static values.
#status:
#  port: 34501
#  user: thin
#  password: thin
